/**
 * EfCoreLibraryAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecentLoanDto } from './recent-loan-dto';


export interface DashboardStatsResponse { 
    totalBooks?: number;
    totalAuthors?: number;
    totalUsers?: number;
    totalLoans?: number;
    recentLoans?: Array<RecentLoanDto>;
}

