/**
 * EfCoreLibraryAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetLoanDto { 
    id?: number;
    date?: string | null;
    plannedReturningDate?: string | null;
    effectiveReturningDate?: string | null;
    bookId?: number;
    bookTitle?: string | null;
    bookReleaseYear?: number;
    bookIsbn?: string | null;
    bookAuthorName?: string | null;
    bookAuthorFirstName?: string | null;
    userId?: number;
    userName?: string | null;
    userFirstName?: string | null;
    userEmail?: string | null;
    userBirthday?: string;
}

