/**
 * EfCoreLibraryAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetLoginDto { 
    id?: number;
    username?: string | null;
    fullName?: string | null;
    password?: string | null;
    salt?: string | null;
}

