/**
 * EfCoreLibraryAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateBookDto { 
    title?: string | null;
    releaseYear?: number;
    isbn?: string | null;
    authorId?: number;
    authorName?: string | null;
    authorFirstName?: string | null;
}

