export * from './authors.service';
import { AuthorsService } from './authors.service';
export * from './books.service';
import { BooksService } from './books.service';
export * from './calendar.service';
import { CalendarService } from './calendar.service';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './loans.service';
import { LoansService } from './loans.service';
export * from './login.service';
import { LoginService } from './login.service';
export * from './logins.service';
import { LoginsService } from './logins.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AuthorsService, BooksService, CalendarService, DashboardService, LoansService, LoginService, LoginsService, UsersService];
